const catalog = document.querySelector('#catalog');
const statusEl = document.querySelector('#status');
const toast = document.querySelector('#toast');
let allItems = [];
function notify(message){toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2600)}
function posterUrl(path){return path?`https://image.tmdb.org/t/p/w500${path}`:''}
function render(items){catalog.innerHTML='';if(!items.length){catalog.innerHTML='<p class="muted">No titles found. Configure TMDB in Render to load live metadata.</p>';return}for(const item of items){const card=document.createElement('article');card.className='tile';const cover=document.createElement('div');cover.className='cover';if(item.posterPath){const img=document.createElement('img');img.loading='lazy';img.alt=item.title||'Title poster';img.src=posterUrl(item.posterPath);cover.append(img)}else{cover.textContent='STREAMIFY';cover.style.display='grid';cover.style.placeItems='center'}const tag=document.createElement('span');tag.className='tag';tag.textContent=item.mediaType==='tv'?'SERIES':'MOVIE';cover.append(tag);const title=document.createElement('h3');title.textContent=item.title||'Untitled';const meta=document.createElement('p');meta.textContent=[item.releaseDate?.slice(0,4),item.originalLanguage?.toUpperCase()].filter(Boolean).join(' · ');card.append(cover,title,meta);card.addEventListener('click',()=>notify('Details and playback will be connected in the next setup stage.'));catalog.append(card)}}
async function load(){try{const response=await fetch('/api/catalog/trending');const data=await response.json();if(!response.ok)throw new Error(data.error||'Catalog unavailable');allItems=data.results||[];statusEl.textContent=`${allItems.length} titles · metadata only`;render(allItems)}catch(error){statusEl.textContent='TMDB setup needed';catalog.innerHTML='<div class="empty"><p>Connect your TMDB API key in Render to load trending titles.</p><p class="muted">This starter does not include video streams.</p></div>';}}
document.querySelectorAll('[data-kind]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-kind]').forEach(x=>x.classList.toggle('active',x===button));const kind=button.dataset.kind;render(kind==='all'?allItems:allItems.filter(x=>x.mediaType===kind));if(kind==='drama'||kind==='anime')notify('This category will be populated by the catalog taxonomy stage.')}));
document.querySelector('#exploreBtn').addEventListener('click',()=>document.querySelector('.section').scrollIntoView({behavior:'smooth'}));document.querySelector('#searchBtn').addEventListener('click',()=>notify('Search UI is planned for the next stage.'));document.querySelector('#profileBtn').addEventListener('click',()=>notify('Guest browsing is enabled. Sign-in will be added for Premium.'));document.querySelector('#premiumBtn').addEventListener('click',()=>notify('Premium plan: ₹99/month. Payment setup is not connected yet.'));
load();
